version: '2'
services:
  webserver:
    image: 303917819930.dkr.ecr.us-west2.amazonaws.com/microservices_webserver
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8000:8000"
    links:
      - processor
      - info
  processor:
    image: 303917819930.dkr.ecr.us-west2.amazonaws.com/microservices_processor
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8082"
  info:
    image: 303917819930.dkr.ecr.us-west2.amazonaws.com/microservices_info
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8092"
